### ISSUE TITLE
Not running on Ubuntu Desktop - error in get_camera_info.py

### ISSUE THREAD

**Issue by jkvarel** [occ-ai/scoresight#12] opened 2024-06-13 12:54 UTC
Hi,

I try to run this app on a Raspberry Pi 5 with Ubuntu Desktop. I build it from source and when I start the executable I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 801, in getSources
    self.update_sources.emit(get_camera_info())
                             ^^^^^^^^^^^^^^^^^
  File "get_camera_info.py", line 67, in get_camera_info
    cameras += get_camera_info_linux()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "get_camera_info.py", line 53, in get_camera_info_linux
    for i, dev in enumerate(device_info)
                            ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'device_info' where it is not associated with a value
```

I tried it with a virtual machine with the same OS on my pc and get the same error.

I think it's not correct that `device_info` is enumerated inside the `device_info` array? And the variables `i` and `dev` are used outside the loop?

https://github.com/occ-ai/scoresight/blob/c3a481503010227452629592e4a711437b78713a/get_camera_info.py#L49-L55

**Comment by Fabelwesen** [comment] 2024-06-15 21:02
+1

same problem here, debian 12, cinnamon2d VM on proxmox.

**Comment by royshil** [comment] 2024-06-17 15:06
can you all please try the artifcats from #14 ?

**Comment by Fabelwesen** [comment] 2024-06-17 20:27
I had to downgrade numpy, but the problem is fixed! 👍 Thank you very much! :)

**Comment by royshil** [comment] 2024-06-17 20:49
closing as resolved

**Closed by royshil** 2024-06-17 20:49 UTC

**Comment by jkvarel** [comment] 2024-06-26 17:09
Yes, it's working now. I had to downgrade numpy, too. From 2.0.0 to 1.26.4

Thank you :)
